version: '3'

services:
  nginx-service:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/project
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php82-service
      - mariadb-service
    networks:
      - nginx-php82-mariadb

  php82-service:
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    container_name: php82-container
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/project
    networks:
      - nginx-php82-mariadb

  mariadb-service:
    image: mariadb
    container_name: mariadb-container
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/mariadb:/var/lib/mysql
    restart: always # always restart unless stopped manually
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: oxyshop
      MARIADB_USER: symfony
      MARIADB_PASSWORD: symfony
    networks:
      - nginx-php82-mariadb

networks:
  nginx-php82-mariadb: